#!C:\Users\lenovo\Documents\test_valsys\valsys-env\Scripts\python.exe
# EASY-INSTALL-SCRIPT: 'pylint==2.3.1','symilar'
__requires__ = 'pylint==2.3.1'
__import__('pkg_resources').run_script('pylint==2.3.1', 'symilar')
